config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post '/step2' => 'users/registrations#step2'
    post '/step3' => 'users/registrations#step3'
  end
  root "welcomes#new"
  get '/user' => 'welcomes#index'
  get 'billing_index' => 'billing#index'
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success

  resources :products, only: [:new, :show, :create,:index]

end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    #debugger
    @product = Product.find_by_id(params[:id])
  end

  def create
    @user = User.find(current_user.id)
    debugger
    @product = @user.products.new(product_params)
    if @product.save
      stripe_product = Stripe::Product.create({name: params[:product][:name]})
      stripe_price = Stripe::Price.create({unit_amount: params[:product][:price],currency: 'usd', product: stripe_product.id ,})
      debugger
      redirect_to products_path
    else
      redirect_to new_product_path
    end
  end



  private
  def product_params
    params.require(:product).permit!
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<center><%= link_to 'Add product', new_product_path%><br></center>
<% @products.each do |f|%>
name: <%= f.name%>&nbsp;&nbsp;&nbsp;
price<%= f.price%>&nbsp;&nbsp;
<%= link_to "show", product_path(f.id)%><br>
<%end%>

app/views/products/new.html.erb
<center> Products 
<%= form_with(model: @product, url: products_path,method: :post) do |f|%>
 <%= f.label 'name:'%>
 <%= f.text_field :name%>

 <%= f.label 'price:'%>
 <%= f.text_field :price%>

 <%= f.submit "Submit" %>

<%end%>
</center>

 

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-md-12 mt-5 text-center">

<%= @product.name%><br>
<%= @product.price%><br>
       add card for payment?
    </h1>
  </div>
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <%= form_tag create_payment_method_path, id: "billing-create-payment-method" do  %>
        <%= link_to "Let's go", add_payment_method_path, remote: true, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>